### ISSUE TITLE
Código Indisponível

### ISSUE THREAD

**Issue by jacsonrbinf** [giuliafgomes36/eng-de-software#2]
Prezadas,

Código indisponível no repositório.

**Comment by giuliafgomes36** [comment]
Boa tarde, professor.

Como conversamos na aula, fizemos um website utilizando a ferramenta wordpress. Ainda não tinha subido para o github mas agora os arquivos do site e o banco de dados encontram-se na release 1.0.0. Ainda, postarei um tutorial para fazer a clonagem do projeto caso o senhor queira simular em máquina local, mandarei o acesso do Wordpress em seu email.

Obrigada.

**Comment by giuliafgomes36** [comment]
O senhor também pode acessar o site criado em: https://giuliafgomes36.github.io/
